import type { Outfit } from './types';

export const mockOutfits: Outfit[] = [
  {
    id: 'outfit-summer-daily-001',
    name: 'Повседневная летняя форма',
    image: '/images/outfits/summer-daily.jpeg',
    season: 'summer',
    purpose: 'daily',
    service: 'general',
    gender: 'male',
    productIds: [
      'cap-summer-001',
      'polo-dark-blue-001',
      'lightweight-trousers-001',
      'black-socks-001',
      'black-shoes-001',
    ],
  },
  {
    id: 'outfit-summer-long-sleeve-001',
    name: 'Летняя форма с длинным рукавом',
    image: '',
    season: 'summer',
    purpose: 'daily',
    service: 'general',
    gender: 'male',
    productIds: [
      'cap-summer-001',
      'summer-suit-jacket-001',
      'summer-suit-trousers-001',
      'black-socks-001',
      'black-shoes-001',
    ],
  },
  {
    id: 'outfit-winter-daily-001',
    name: 'Повседневная зимняя форма',
    image: '',
    season: 'winter',
    purpose: 'daily',
    service: 'general',
    gender: 'male',
    productIds: [],
  },
  {
    id: 'outfit-summer-female-001',
    name: 'Летний повседневный комплект женский',
    image: '',
    season: 'summer',
    purpose: 'daily',
    service: 'general',
    gender: 'female',
    productIds: [
      'female-blouse-dark-blue-001',
      'female-skirt-dark-blue-001',
      'female-shoes-black-001',
    ],
  },
  {
    id: 'outfit-summer-dress-female-001',
    name: 'Летний форменный комплект с платьем',
    image: '',
    season: 'summer',
    purpose: 'daily',
    service: 'general',
    gender: 'female',
    productIds: ['female-summer-dress-001', 'female-cotton-hosiery-001'],
  },
  {
    id: 'outfit-dps-daily-001',
    name: 'Комплект для службы ДПС',
    image: '',
    season: 'demi-season',
    purpose: 'special',
    service: 'dps',
    gender: 'unisex',
    productIds: ['dps-signal-jacket-001', 'dps-vest-high-visibility-001', 'dps-tactical-shirt-001'],
  },
  {
    id: 'outfit-pps-daily-001',
    name: 'Повседневный комплект ППС',
    image: '',
    season: 'demi-season',
    purpose: 'daily',
    service: 'pps',
    gender: 'unisex',
    productIds: ['pps-tactical-suit-001', 'pps-tactical-shirt-001'],
  },
  {
    id: 'outfit-dps-motorcycle-001',
    name: 'Комплект для службы ДПС на мотоцикле',
    image: '',
    season: 'demi-season',
    purpose: 'special',
    service: 'dps',
    gender: 'unisex',
    productIds: ['dps-motorcycle-demi-suit-001'],
  },
];
