import type { Product } from './types';

type CatalogProduct = Omit<Product, 'gender' | 'services' | 'entitlements'> &
  Partial<Pick<Product, 'gender' | 'services' | 'entitlements'>>;

const catalogProducts: CatalogProduct[] = [
  {
    id: 'cap-summer-001',
    name: 'Кепи летнее нового образца',
    description: 'Летнее форменное кепи темно-синего цвета нового образца.',
    image: '/images/products/cap-summer.png',
    categoryId: 'headwear',
    subsCategoryId: 'caps',
    season: 'summer',
    availableSizes: ['56', '57', '58', '59', '60'],
    entitlements: [
      {
        norm: '2',
        period: { value: 3, unit: 'years' },
        quantity: '1 штука',
        periodOverrides: [
          {
            requiredDuties: ['traffic-supervision'],
            period: { value: 1, unit: 'years' },
            note: 'Для сотрудников, осуществляющих надзор за дорожным движением.',
          },
          {
            requiredDuties: ['external-service'],
            period: { value: 2, unit: 'years' },
            note: 'Для сотрудников, несущих наружную службу (кроме надзора за дорожным движением).',
          },
        ],
        note: 'Срок зависит от примечаний к норме и характера службы.',
      },
    ],
  },
  {
    id: 'cap-wool-001',
    name: 'Фуражка шерстяная темно-синего цвета',
    description:
      'Фуражка повседневной формы одежды. Конкретный вариант зависит от категории сотрудника и применимой нормы снабжения.',
    image: '/images/products/peaked-cap-wool.jpg',
    categoryId: 'headwear',
    subsCategoryId: 'caps',
    season: 'all-season',
    availableSizes: ['56', '57', '58', '59', '60'],
  },
  {
    id: 'ushanka-winter-001',
    name: 'Шапка-ушанка меховая из овчины темно-синего цвета',
    description:
      'Зимний головной убор. Конкретный вариант зависит от категории сотрудника и применимой нормы снабжения.',
    image: '/images/products/ushanka-winter.jpg',
    categoryId: 'headwear',
    subsCategoryId: 'caps',
    season: 'winter',
    availableSizes: ['56', '57', '58', '59', '60'],
  },
  {
    id: 'polo-dark-blue-001',
    name: 'Поло форменное темно-синее',
    description: 'Форменное поло темно-синего цвета для летнего периода.',
    image: '/images/products/polo-dark-blue.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'polo',
    season: 'summer',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
  },
  {
    id: 'summer-lightweight-jacket-001',
    name: 'Куртка повседневного облегченного костюма',
    description: 'Облегченная куртка повседневного костюма темно-синего цвета.',
    image: '/images/products/summer-lightweight-jacket.jpg',
    categoryId: 'outerwear',
    subsCategoryId: 'summer-outerwear',
    season: 'summer',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
  },
  {
    id: 'summer-suit-jacket-001',
    name: 'Куртка летнего костюма',
    description: 'Куртка летнего костюма темно-синего цвета с длинными рукавами.',
    image: '/images/products/summer-suit-jacket.jpg',
    categoryId: 'outerwear',
    subsCategoryId: 'summer-outerwear',
    season: 'summer',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
  },
  {
    id: 'lightweight-trousers-001',
    name: 'Брюки повседневного облегченного костюма',
    description: 'Брюки повседневного облегченного костюма темно-синего цвета.',
    image: '/images/products/lightweight-trousers.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'trousers',
    season: 'summer',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
  },
  {
    id: 'summer-suit-trousers-001',
    name: 'Брюки летнего костюма',
    description: 'Брюки летнего костюма темно-синего цвета.',
    image: '/images/products/summer-suit-trousers.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'trousers',
    season: 'summer',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
  },
  {
    id: 'tshirt-dark-blue-001',
    name: 'Футболка темно-синяя',
    description: 'Футболка темно-синего цвета для ношения под форменной одеждой.',
    image: '/images/products/tshirt-dark-blue.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'tshirts',
    season: 'summer',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
  },
  {
    id: 'tshirt-white-001',
    name: 'Футболка белая',
    description: 'Футболка белого цвета для летнего периода.',
    image: '/images/products/tshirt-white.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'tshirts',
    season: 'summer',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
  },
  {
    id: 'trouser-belt-001',
    name: 'Ремень брючный',
    description: 'Брючный ремень черного цвета.',
    image: '/images/products/trouser-belt.jpg',
    categoryId: 'accessories',
    subsCategoryId: 'belts',
    season: 'summer',
    availableSizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'waist-belt-001',
    name: 'Ремень поясной кожаный',
    description: 'Поясной кожаный ремень черного цвета.',
    image: '/images/products/waist-belt.jpg',
    categoryId: 'equipment',
    subsCategoryId: 'belts',
    season: 'summer',
    availableSizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'black-socks-001',
    name: 'Носки черные',
    description: 'Форменные носки черного цвета.',
    image: '/images/products/black-socks.jpg',
    categoryId: 'accessories',
    subsCategoryId: 'socks',
    season: 'summer',
    availableSizes: ['25', '27', '29'],
  },
  {
    id: 'black-shoes-001',
    name: 'Полуботинки черные',
    description: 'Форменные полуботинки черного цвета.',
    image: '/images/products/black-shoes.jpg',
    categoryId: 'footwear',
    subsCategoryId: 'low-shoes',
    season: 'summer',
    availableSizes: ['39', '40', '41', '42', '43', '44', '45'],
  },
  {
    id: 'lightweight-boots-001',
    name: 'Ботинки с высокими берцами облегченные',
    description: 'Облегченные ботинки с высокими берцами черного цвета.',
    image: '/images/products/lightweight-boots.jpg',
    categoryId: 'footwear',
    subsCategoryId: 'boots',
    season: 'summer',
    availableSizes: ['39', '40', '41', '42', '43', '44', '45'],
  },
  {
    id: 'female-blouse-dark-blue-001',
    name: 'Блузка форменная женская',
    description: 'Блузка из нормы снабжения вещевым имуществом женщин № 4.',
    image: '/images/products/female-blouse-dark-blue.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'shirts',
    season: 'all-season',
    availableSizes: ['42', '44', '46', '48', '50', '52'],
    gender: 'female',
    entitlements: [
      {
        norm: '4',
        period: { value: 2, unit: 'years' },
        quantity: '4 штуки',
        periodAdjustments: [{ norm: '17', years: 1 }],
        note: 'При обеспечении по норме № 17 срок увеличивается на 1 год.',
      },
    ],
  },
  {
    id: 'female-cap-summer-001',
    name: 'Кепи летнее женское',
    description: 'Женская позиция нормы снабжения вещевым имуществом № 4.',
    image: '/images/products/female-cap-summer.jpg',
    categoryId: 'headwear',
    subsCategoryId: 'caps',
    season: 'summer',
    availableSizes: ['54', '55', '56', '57', '58', '59'],
    gender: 'female',
    entitlements: [
      {
        norm: '4',
        period: { value: 3, unit: 'years' },
        quantity: '1 штука',
        periodOverrides: [
          {
            requiredDuties: ['traffic-supervision'],
            period: { value: 1, unit: 'years' },
            note: 'Для сотрудников, осуществляющих надзор за дорожным движением.',
          },
          {
            requiredDuties: ['external-service'],
            period: { value: 2, unit: 'years' },
            note: 'Для сотрудников, несущих наружную службу (кроме надзора за дорожным движением).',
          },
        ],
        note: 'Срок зависит от примечаний к норме и характера службы.',
      },
    ],
  },
  {
    id: 'female-skirt-dark-blue-001',
    name: 'Костюм (куртка с короткими рукавами и юбка) повседневный облегченный',
    description: 'Предмет нормы снабжения вещевым имуществом женщин № 4.',
    image: '/images/products/female-skirt-dark-blue.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'service-suits',
    season: 'summer',
    availableSizes: ['42', '44', '46', '48', '50', '52'],
    gender: 'female',
    entitlements: [
      { norm: '4', period: { value: 2, unit: 'years' }, quantity: '1 комплект' },
    ],
  },
  {
    id: 'female-trousers-dark-blue-001',
    name: 'Костюм (куртка с длинными рукавами и брюки) повседневный',
    description: 'Предмет нормы снабжения вещевым имуществом женщин № 4.',
    image: '/images/products/female-trousers-dark-blue.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'service-suits',
    season: 'all-season',
    availableSizes: ['42', '44', '46', '48', '50', '52'],
    gender: 'female',
    entitlements: [
      { norm: '4', period: { value: 2, unit: 'years' }, quantity: '1 комплект' },
    ],
  },
  {
    id: 'female-summer-jacket-001',
    name: 'Куртка летнего костюма женская',
    description: 'Куртка летнего форменного костюма женского кроя.',
    image: '/images/products/female-summer-jacket.jpg',
    categoryId: 'outerwear',
    subsCategoryId: 'summer-outerwear',
    season: 'summer',
    availableSizes: ['42', '44', '46', '48', '50', '52'],
    gender: 'female',
    entitlements: [],
  },
  {
    id: 'female-shoes-black-001',
    name: 'Туфли форменные женские черные',
    description: 'Черные форменные туфли женской модели.',
    image: '/images/products/female-shoes-black.jpg',
    categoryId: 'footwear',
    subsCategoryId: 'low-shoes',
    season: 'all-season',
    availableSizes: ['35', '36', '37', '38', '39', '40', '41'],
    gender: 'female',
    entitlements: [],
  },
  {
    id: 'dps-vest-high-visibility-001',
    name: 'Жилет сигнальный с элементами из световозвращающих материалов',
    description: 'Предмет особой формы одежды из нормы снабжения № 10.',
    image: '/images/products/dps-vest-high-visibility.jpg',
    categoryId: 'equipment',
    subsCategoryId: 'high-visibility',
    season: 'all-season',
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    services: ['dps'],
    gender: 'unisex',
    entitlements: [
      {
        norm: '10',
        period: { value: 1, unit: 'years' },
        quantity: '1 штука',
        requiredDuties: ['traffic-supervision'],
      },
    ],
  },
  {
    id: 'dps-signal-jacket-001',
    name: 'Куртка сигнальная с элементами из световозвращающих материалов',
    description: 'Предмет особой формы одежды из нормы снабжения № 10.',
    image: '/images/products/dps-signal-jacket.jpg',
    categoryId: 'outerwear',
    subsCategoryId: 'service-outerwear',
    season: 'all-season',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
    services: ['dps'],
    gender: 'unisex',
    entitlements: [
      {
        norm: '10',
        period: { value: 2, unit: 'years' },
        quantity: '1 штука',
        requiredDuties: ['traffic-supervision'],
      },
    ],
  },
  {
    id: 'dps-tactical-shirt-001',
    name: 'Рубашка тактическая комбинированная темно-синего и желтого флуоресцентного цвета',
    description: 'Рубашка с элементами из световозвращающих материалов из нормы снабжения № 10.',
    image: '/images/products/dps-tactical-shirt.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'shirts',
    season: 'summer',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
    services: ['dps'],
    gender: 'unisex',
    entitlements: [
      {
        norm: '10',
        period: { value: 1, unit: 'years' },
        quantity: '2 штуки',
        requiredDuties: ['traffic-supervision'],
      },
    ],
  },
  {
    id: 'dps-motorcycle-demi-suit-001',
    name: 'Костюм демисезонный для несения службы на мотоцикле',
    description: 'Предмет нормы снабжения № 10 для сотрудников, несущих службу на мотоциклах.',
    image: '/images/products/dps-motorcycle-demi-suit.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'service-suits',
    season: 'demi-season',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
    services: ['dps'],
    gender: 'unisex',
    entitlements: [
      {
        norm: '10',
        period: { value: 2, unit: 'years' },
        quantity: '1 комплект',
        requiredDuties: ['motorcycle'],
      },
    ],
  },
  {
    id: 'dps-motorcycle-summer-suit-001',
    name: 'Костюм летний для несения службы на мотоцикле',
    description: 'Предмет нормы снабжения № 10 для сотрудников, несущих службу на мотоциклах.',
    image: '/images/products/dps-motorcycle-summer-suit.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'service-suits',
    season: 'summer',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
    services: ['dps'],
    gender: 'unisex',
    entitlements: [
      {
        norm: '10',
        period: { value: 1, unit: 'years' },
        quantity: '1 комплект',
        requiredDuties: ['motorcycle'],
      },
    ],
  },
  {
    id: 'pps-tactical-suit-001',
    name: 'Костюм летний тактический темно-синего цвета',
    description: 'Предмет особой формы одежды строевых подразделений ППС по норме снабжения № 17.',
    image: '/images/products/pps-tactical-suit.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'service-suits',
    season: 'summer',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
    services: ['pps'],
    gender: 'unisex',
    entitlements: [
      {
        norm: '17',
        period: { value: 1, unit: 'years' },
        quantity: '1 комплект',
        requiredDuties: ['pps-line'],
        excludedConditions: ['hot-climate', 'special-regiment'],
      },
    ],
  },
  {
    id: 'pps-tactical-shirt-001',
    name: 'Рубашка тактическая темно-синего цвета',
    description: 'Предмет особой формы одежды строевых подразделений ППС по норме снабжения № 17.',
    image: '/images/products/pps-tactical-shirt.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'shirts',
    season: 'all-season',
    availableSizes: ['46-3', '48-3', '50-3', '52-3', '54-3'],
    services: ['pps'],
    gender: 'unisex',
    entitlements: [
      {
        norm: '17',
        period: { value: 1, unit: 'years' },
        quantity: '2 штуки',
        requiredDuties: ['pps-line'],
        excludedConditions: ['hot-climate', 'special-regiment'],
      },
    ],
  },
  {
    id: 'female-summer-dress-001',
    name: 'Платье летнее женское',
    description: 'Платье летнее из нормы снабжения вещевым имуществом женщин № 4.',
    image: '/images/products/female-summer-dress.jpg',
    categoryId: 'uniform',
    subsCategoryId: 'dresses',
    season: 'summer',
    availableSizes: ['42', '44', '46', '48', '50', '52'],
    gender: 'female',
    entitlements: [
      { norm: '4', period: { value: 3, unit: 'years' }, quantity: '1 штука' },
    ],
  },
  {
    id: 'female-cotton-hosiery-001',
    name: 'Носки хлопчатобумажные (колготки)',
    description: 'Женская позиция нормы снабжения № 4.',
    image: '/images/products/female-cotton-hosiery.jpg',
    categoryId: 'accessories',
    subsCategoryId: 'hosiery',
    season: 'all-season',
    availableSizes: ['S', 'M', 'L', 'XL'],
    gender: 'female',
    entitlements: [
      {
        norm: '4',
        period: { value: 1, unit: 'years' },
        quantity: '1 пара',
        periodAdjustments: [{ norm: '17', years: 1 }],
        note: 'При обеспечении по норме № 17 срок увеличивается на 1 год.',
      },
    ],
  },
  {
    id: 'female-wool-hosiery-001',
    name: 'Носки шерстяные (колготки)',
    description: 'Женская позиция нормы снабжения № 4.',
    image: '/images/products/female-wool-hosiery.jpg',
    categoryId: 'accessories',
    subsCategoryId: 'hosiery',
    season: 'winter',
    availableSizes: ['S', 'M', 'L', 'XL'],
    gender: 'female',
    entitlements: [
      {
        norm: '4',
        period: { value: 1, unit: 'years' },
        quantity: '1 пара',
        periodAdjustments: [{ norm: '17', years: 1 }],
        note: 'При обеспечении по норме № 17 срок увеличивается на 1 год.',
      },
    ],
  },
];

export const mockProducts: Product[] = catalogProducts.map((product) => ({
  ...product,
  gender: product.gender ?? 'male',
  services: product.services ?? ['general'],
  entitlements: product.entitlements ?? [],
}));
